# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d91b842ae00400a8d689f0dd33caa3bda3b340c6470edb4a7a97c53e71135c99aabc9d9ac5ad41aefd989f5f310b0d5ac92ad4d2a4e048a572962dc32e8fc79

test:
  secret_key_base: 3325cb400ab06cfd248d79d33b621a1fd8b24d839f79d187e208f1936a87f1f486cc90c89c2049e1253871e6e76e7193e09952b231d282988958232bd93e1710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
